#include <vsg/all.h>

#ifdef vsgXchange_FOUND
#    include <vsgXchange/all.h>
#endif

#ifdef vsgImGui_FOUND
#include <vsgImGui/RenderImGui.h>
#include <vsgImGui/SendEventsToImGui.h>
#endif

#include <algorithm>
#include <chrono>
#include <iostream>
#include <thread>

vsg::ref_ptr<vsg::Node> createTextureQuad(vsg::ref_ptr<vsg::Data> sourceData, vsg::ref_ptr<vsg::Options> options)
{
    auto builder = vsg::Builder::create();
    builder->options = options;

    vsg::StateInfo state;
    state.image = sourceData;
    state.lighting = false;

    vsg::GeometryInfo geom;
    geom.dy.set(0.0f, 0.0f, 1.0f);
    geom.dz.set(0.0f, -1.0f, 0.0f);

    return builder->createQuad(geom, state);
}

void enableGenerateDebugInfo(vsg::ref_ptr<vsg::Options> options)
{
    auto shaderHints = vsg::ShaderCompileSettings::create();
    shaderHints->generateDebugInfo = true;

    auto& text = options->shaderSets["text"] = vsg::createTextShaderSet(options);
    text->defaultShaderHints = shaderHints;

    auto& flat = options->shaderSets["flat"] = vsg::createFlatShadedShaderSet(options);
    flat->defaultShaderHints = shaderHints;

    auto& phong = options->shaderSets["phong"] = vsg::createPhongShaderSet(options);
    phong->defaultShaderHints = shaderHints;

    auto& pbr = options->shaderSets["pbr"] = vsg::createPhysicsBasedRenderingShaderSet(options);
    pbr->defaultShaderHints = shaderHints;
}

#ifdef vsgImGui_FOUND
class ComponentBase : public vsgImGui::RenderImGui::Component
{
public:
    vsgImGui::RenderImGui::Component& component() { return _component; }

protected:
    virtual bool drawComponent() { return false; }
    vsgImGui::RenderImGui::Component _component;

};

class EventHandlerBase : public ComponentBase, public vsg::Inherit<vsgImGui::SendEventsToImGui, EventHandlerBase>
{
public:
    void setKey(vsg::KeySymbol actionKey, const std::string& helpText = std::string())
    {
        ImGuiIO& io = ImGui::GetIO();
        io.WantCaptureKeyboard = true;
        KeyAndModifier key(actionKey, vsg::KeyModifier());
        if (_vsgToIntermediateMap.find(key) == _vsgToIntermediateMap.end()) {
            uint16_t imKey;
            switch(actionKey)
            {
                case vsg::KEY_h: imKey = ImGuiKey_H; break;
                case vsg::KEY_s: imKey = ImGuiKey_S; break;
                case vsg::KEY_Escape: imKey = ImGuiKey_Escape; break;
                default: throw vsg::Exception{std::string("undefined key mapping for vsgImGui")};
            }
            std::cerr << __FUNCTION__ << imKey << " " <<  actionKey << std::endl;
            _assignKeyMapping(imKey, actionKey);
        }
        _actionKey = actionKey;
        _helpTexts.push_back(helpText);
        _helpTexts.sort();
    }

    bool enabled() const { return _enabled; }

    const std::list<std::string>& helpTexts() const { return _helpTexts; }

protected:
    vsg::KeySymbol _actionKey{vsg::KEY_Undefined};
    bool _enabled{false};
    static std::list<std::string> _helpTexts;

    void apply(vsg::KeyPressEvent& keyPress) override
    {
        if (_actionKey != vsg::KEY_Undefined && keyPress.keyBase == _actionKey)
            _enabled = !_enabled;
    }
};

std::list<std::string> EventHandlerBase::_helpTexts;

/// CloseHandler event handler used to respond to close events generated by a Window.
class CloseHandler : public vsg::Inherit<EventHandlerBase, CloseHandler>
{
public:
    explicit CloseHandler(vsg::Viewer* viewer) :
        _viewer(viewer)
    {
        setKey(vsg::KEY_Escape, "Escape - quit application");
    }

    virtual void close()
    {
        // take a ref_ptr<> of the oberserv_ptr<> to be able to safely access it
        vsg::ref_ptr<vsg::Viewer> viewer = _viewer;
        if (viewer) viewer->close();
    }

    void apply(vsg::CloseWindowEvent&) override
    {
        close();
    }

    void apply(vsg::KeyPressEvent& keyPress) override
    {
        EventHandlerBase::apply(keyPress);
        if (enabled())
            close();
    }

    void apply(vsg::TerminateEvent&) override
    {
        close();
    }

protected:
    // use observer_ptr<> to avoid circular reference
    vsg::observer_ptr<vsg::Viewer> _viewer;
};

class HelpHandler : public vsg::Inherit<EventHandlerBase, HelpHandler>
{
public:
    explicit HelpHandler()
    {
        setKey(vsg::KEY_h, "h - show help");
        _component = std::bind(&HelpHandler::drawComponent, this);
    }

    bool drawComponent() override
    {
        if (!_enabled)
            return false;
        ImGui::SetNextWindowBgAlpha(0.0f);
        ImGui::Begin("Help", NULL, ImGuiWindowFlags_AlwaysAutoResize);
        for (const std::string& text : helpTexts())
            ImGui::Text("%s", text.c_str());
        ImGui::End();
        return true;
    }
};

class StatisticsHandler : public vsg::Inherit<EventHandlerBase, StatisticsHandler>
{
public:
    StatisticsHandler()
    {
        setKey(vsg::KEY_s, "s - show statistics");
        _component = std::bind(&StatisticsHandler::drawComponent, this);
    }

    bool drawComponent() override
    {
        if (!_enabled)
            return false;
        ImGui::SetNextWindowBgAlpha(0.0f);
        ImGui::Begin("Statistics");
        ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
        ImGui::End();
        return true;
    }
};
#endif

int main(int argc, char** argv)
{
    try
    {
        // set up defaults and read command line arguments to override them
        vsg::CommandLine arguments(&argc, argv);

        // set up vsg::Options to pass in filepaths and ReaderWriter's and other IO related options to use when reading and writing files.
        auto options = vsg::Options::create();
        options->sharedObjects = vsg::SharedObjects::create();
        options->fileCache = vsg::getEnv("VSG_FILE_CACHE");
        options->paths = vsg::getEnvPaths("VSG_FILE_PATH");

#ifdef vsgXchange_all
        // add vsgXchange's support for reading and writing 3rd party file formats
        options->add(vsgXchange::all::create());
#endif

        arguments.read(options);

        auto windowTraits = vsg::WindowTraits::create();
        windowTraits->windowTitle = "vsgviewer";
        windowTraits->debugLayer = arguments.read({"--debug", "-d"});
        windowTraits->apiDumpLayer = arguments.read({"--api", "-a"});
        windowTraits->synchronizationLayer = arguments.read("--sync");
        bool reportAverageFrameRate = arguments.read("--fps");
        if (int mt = 0; arguments.read({"--memory-tracking", "--mt"}, mt)) vsg::Allocator::instance()->setMemoryTracking(mt);
        if (arguments.read("--double-buffer")) windowTraits->swapchainPreferences.imageCount = 2;
        if (arguments.read("--triple-buffer")) windowTraits->swapchainPreferences.imageCount = 3; // default
        if (arguments.read("--IMMEDIATE")) { windowTraits->swapchainPreferences.presentMode = VK_PRESENT_MODE_IMMEDIATE_KHR; }
        if (arguments.read("--FIFO")) windowTraits->swapchainPreferences.presentMode = VK_PRESENT_MODE_FIFO_KHR;
        if (arguments.read("--FIFO_RELAXED")) windowTraits->swapchainPreferences.presentMode = VK_PRESENT_MODE_FIFO_RELAXED_KHR;
        if (arguments.read("--MAILBOX")) windowTraits->swapchainPreferences.presentMode = VK_PRESENT_MODE_MAILBOX_KHR;
        if (arguments.read({"-t", "--test"}))
        {
            windowTraits->swapchainPreferences.presentMode = VK_PRESENT_MODE_IMMEDIATE_KHR;
            windowTraits->fullscreen = true;
            reportAverageFrameRate = true;
        }
        if (arguments.read({"--st", "--small-test"}))
        {
            windowTraits->swapchainPreferences.presentMode = VK_PRESENT_MODE_IMMEDIATE_KHR;
            windowTraits->width = 192, windowTraits->height = 108;
            windowTraits->decoration = false;
            reportAverageFrameRate = true;
        }

        if (arguments.read({"--fullscreen", "--fs"})) windowTraits->fullscreen = true;
        if (arguments.read({"--window", "-w"}, windowTraits->width, windowTraits->height)) { windowTraits->fullscreen = false; }
        if (arguments.read({"--no-frame", "--nf"})) windowTraits->decoration = false;
        if (arguments.read("--or")) windowTraits->overrideRedirect = true;
        if (arguments.read("--d32")) windowTraits->depthFormat = VK_FORMAT_D32_SFLOAT;
        arguments.read("--screen", windowTraits->screenNum);
        arguments.read("--display", windowTraits->display);
        arguments.read("--samples", windowTraits->samples);
        auto numFrames = arguments.value(-1, "-f");
        auto pathFilename = arguments.value(std::string(), "-p");
        auto loadLevels = arguments.value(0, "--load-levels");
        auto maxPagedLOD = arguments.value(0, "--maxPagedLOD");
        auto horizonMountainHeight = arguments.value(0.0, "--hmh");
        auto nearFarRatio = arguments.value<double>(0.001, "--nfr");
        if (arguments.read("--rgb")) options->mapRGBtoRGBAHint = false;

        if (arguments.read({"--shader-debug-info", "--sdi"}))
        {
            enableGenerateDebugInfo(options);
            windowTraits->deviceExtensionNames.push_back(VK_KHR_SHADER_NON_SEMANTIC_INFO_EXTENSION_NAME);
        }

        if (int log_level = 0; arguments.read("--log-level", log_level)) vsg::Logger::instance()->level = vsg::Logger::Level(log_level);

        if (arguments.errors()) return arguments.writeErrorMessages(std::cerr);

        if (argc <= 1)
        {
            std::cout << "Please specify a 3d model or image file on the command line." << std::endl;
            return 1;
        }

        auto group = vsg::Group::create();

        vsg::Path path;

        // read any vsg files
        for (int i = 1; i < argc; ++i)
        {
            vsg::Path filename = arguments[i];
            path = vsg::filePath(filename);

            auto object = vsg::read(filename, options);
            if (auto node = object.cast<vsg::Node>())
            {
                group->addChild(node);
            }
            else if (auto data = object.cast<vsg::Data>())
            {
                if (auto textureGeometry = createTextureQuad(data, options))
                {
                    group->addChild(textureGeometry);
                }
            }
            else if (object)
            {
                std::cout << "Unable to view object of type " << object->className() << std::endl;
            }
            else
            {
                std::cout << "Unable to load file " << filename << std::endl;
            }
        }

        if (group->children.empty())
        {
            return 1;
        }

        vsg::ref_ptr<vsg::Node> vsg_scene;
        if (group->children.size() == 1)
            vsg_scene = group->children[0];
        else
            vsg_scene = group;

        // create the viewer and assign window(s) to it
        auto viewer = vsg::Viewer::create();
        auto window = vsg::Window::create(windowTraits);
        if (!window)
        {
            std::cout << "Could not create windows." << std::endl;
            return 1;
        }

        viewer->addWindow(window);

        // compute the bounds of the scene graph to help position camera
        vsg::ComputeBounds computeBounds;
        vsg_scene->accept(computeBounds);
        vsg::dvec3 centre = (computeBounds.bounds.min + computeBounds.bounds.max) * 0.5;
        double radius = vsg::length(computeBounds.bounds.max - computeBounds.bounds.min) * 0.6;

        // set up the camera
        auto lookAt = vsg::LookAt::create(centre + vsg::dvec3(0.0, -radius * 3.5, 0.0), centre, vsg::dvec3(0.0, 0.0, 1.0));

        vsg::ref_ptr<vsg::ProjectionMatrix> perspective;
        auto ellipsoidModel = vsg_scene->getRefObject<vsg::EllipsoidModel>("EllipsoidModel");
        if (ellipsoidModel)
        {
            perspective = vsg::EllipsoidPerspective::create(lookAt, ellipsoidModel, 30.0, static_cast<double>(window->extent2D().width) / static_cast<double>(window->extent2D().height), nearFarRatio, horizonMountainHeight);
        }
        else
        {
            perspective = vsg::Perspective::create(30.0, static_cast<double>(window->extent2D().width) / static_cast<double>(window->extent2D().height), nearFarRatio * radius, radius * 4.5);
        }

        auto camera = vsg::Camera::create(perspective, lookAt, vsg::ViewportState::create(window->extent2D()));

        if (pathFilename.empty())
        {
            viewer->addEventHandler(vsg::Trackball::create(camera, ellipsoidModel));
        }
        else
        {
            auto animationPath = vsg::read_cast<vsg::AnimationPath>(pathFilename, options);
            if (!animationPath)
            {
                std::cout<<"Warning: unable to read animation path : "<<pathFilename<<std::endl;
                return 1;
            }

            auto animationPathHandler = vsg::AnimationPathHandler::create(camera, animationPath, viewer->start_point());
            animationPathHandler->printFrameStatsToConsole = true;
            viewer->addEventHandler(animationPathHandler);
        }

        // if required preload specific number of PagedLOD levels.
        if (loadLevels > 0)
        {
            vsg::LoadPagedLOD loadPagedLOD(camera, loadLevels);

            auto startTime = vsg::clock::now();

            vsg_scene->accept(loadPagedLOD);

            auto time = std::chrono::duration<float, std::chrono::milliseconds::period>(vsg::clock::now() - startTime).count();
            std::cout << "No. of tiles loaded " << loadPagedLOD.numTiles << " in " << time << "ms." << std::endl;
        }

        auto commandGraph = vsg::CommandGraph::create(window);
        auto renderGraph = createRenderGraphForView(window, camera, vsg_scene);
        commandGraph->addChild(renderGraph);

#ifdef vsgImGui_FOUND
        // the RenderImGui instance must be created before each event handler
        vsg::ref_ptr<vsgImGui::RenderImGui> renderImGui = vsgImGui::RenderImGui::create(window);
        vsg::ref_ptr<EventHandlerBase> helpHandler = HelpHandler::create();
        vsg::ref_ptr<EventHandlerBase> statisticsHandler = StatisticsHandler::create();

        renderImGui->add(helpHandler->component());
        renderImGui->add(statisticsHandler->component());
        renderGraph->addChild(renderImGui);

        // add close handler to respond the close window button and pressing escape
        viewer->addEventHandler(CloseHandler::create(viewer));
        // add handler to show the help page
        viewer->addEventHandler(helpHandler);
        // add handler to show for example the frame rate
        viewer->addEventHandler(statisticsHandler);
#else
        // add close handler to respond the close window button and pressing escape
        viewer->addEventHandler(vsg::CloseHandler::create(viewer));
#endif
        viewer->assignRecordAndSubmitTaskAndPresentation({commandGraph});

        viewer->compile();

        if (maxPagedLOD > 0)
        {
            // set targetMaxNumPagedLODWithHighResSubgraphs after Viewer::compile() as it will assign any DatabasePager if required.
            for(auto& task : viewer->recordAndSubmitTasks)
            {
                if (task->databasePager) task->databasePager->targetMaxNumPagedLODWithHighResSubgraphs = maxPagedLOD;
            }
        }

        viewer->start_point() = vsg::clock::now();

        // rendering main loop
        while (viewer->advanceToNextFrame() && (numFrames < 0 || (numFrames--) > 0))
        {
            // pass any events into EventHandlers assigned to the Viewer
            viewer->handleEvents();

            viewer->update();

            viewer->recordAndSubmit();

            viewer->present();
        }

        if (reportAverageFrameRate)
        {
            auto fs = viewer->getFrameStamp();
            double fps = static_cast<double>(fs->frameCount) / std::chrono::duration<double, std::chrono::seconds::period>(vsg::clock::now() - viewer->start_point()).count();
            std::cout<<"Average frame rate = "<<fps<<" fps"<<std::endl;
        }
    }
    catch (const vsg::Exception& ve)
    {
        for (int i = 0; i < argc; ++i) std::cerr << argv[i] << " ";
        std::cerr << "\n[Exception] - " << ve.message << " result = " << ve.result << std::endl;
        return 1;
    }

    // clean up done automatically thanks to ref_ptr<>
    return 0;
}
